#ifndef H_RAYTRAYCING_CONSTANTS
#define H_RAYTRAYCING_CONSTANTS

#define W_COLS 900
#define W_ROWS 700
#define FLAT_ENVIRONMENT_LENGTH W_COLS * W_ROWS
#define COLOR_BLACK 0x000000
#define COLOR_WHITE 0xFFFFFF
#define COLOR_GRAY 0x0A0A0A
#define COLOR_BLUE 0x0000FF
#define COLOR_GREEN 0x00FF00
#define COLOR_RED 0xFF0000
#define COLOR_PURPLE 0X78056A
#define COLOR_YELLOW 0xFCD703
#define COLOR_YELLOW_LIGHT 0xFFF2AB
#define COLOR_GRAY_LIGHT 0x0F0F0F
#define CIRCLE_BORDER_PADDING 5
#define PLAYER_SPEED 5

#endif
